public sealed record FiiDto(
    int RankPvp,
    int RankDy,
    decimal RankLevel,
    string Papel,
    string Segmento,
    decimal PrecoParaComprar,
    decimal FfoYield,
    decimal DividendYield,
    decimal Pvp,
    decimal ValorMercado,
    decimal Liquidez,
    int QuantidadeImoveis,
    decimal PrecoMetroQuadrado,
    decimal AluguelMetroQuadrado,
    decimal CapRate,
    decimal VacanciaMedia,
    decimal DividendoPorCota,
    decimal DyMensal,
    decimal ProventoMensalPorCota,
    decimal ProventoDiarioPorCota,
    decimal ReceberPorMes,
    decimal ReceberPorDia,
    int QtdCotasNumeroMagico,
    decimal ValorParaNumeroMagico,
    decimal InvestirParaNumeroMagico,
    string Tipo,
    string[] Motivos
);


